import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react"
import {
  ClerkProvider
} from "@clerk/nextjs"
import db from "@/utils/db.ts"
import {
  syncUser
} from "@/actions/user.action"



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "IdeaBuddy",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  await db()

  await syncUser()

  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
        </head>
        <body>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
